// Code generated by pgxgen. DO NOT EDIT.
package repo_digestrun

import (
	"github.com/gobeam/stringy"
	"strings"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameDigestRuns TableName = "digest_runs"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameDigestRunsId               ColumnName = "id"
	ColumnNameDigestRunsTeam             ColumnName = "team"
	ColumnNameDigestRunsSlot             ColumnName = "slot"
	ColumnNameDigestRunsRunDate          ColumnName = "run_date"
	ColumnNameDigestRunsAttempt          ColumnName = "attempt"
	ColumnNameDigestRunsStatus           ColumnName = "status"
	ColumnNameDigestRunsParts            ColumnName = "parts"
	ColumnNameDigestRunsMrCount          ColumnName = "mr_count"
	ColumnNameDigestRunsError            ColumnName = "error"
	ColumnNameDigestRunsCreatedAt        ColumnName = "created_at"
	ColumnNameDigestRunsLinearIssueCount ColumnName = "linear_issue_count"
)

func DigestRunsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameDigestRunsId,
		ColumnNameDigestRunsTeam,
		ColumnNameDigestRunsSlot,
		ColumnNameDigestRunsRunDate,
		ColumnNameDigestRunsAttempt,
		ColumnNameDigestRunsStatus,
		ColumnNameDigestRunsParts,
		ColumnNameDigestRunsMrCount,
		ColumnNameDigestRunsError,
		ColumnNameDigestRunsCreatedAt,
		ColumnNameDigestRunsLinearIssueCount,
	}
}
