// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest_runs_gen.sql

package repo_digestrun

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sxwebdev/ai-reviewer/internal/models"
)

const create = `-- name: Create :one
INSERT INTO digest_runs (team, slot, run_date, attempt, status, parts, mr_count, error)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
	RETURNING id, team, slot, run_date, attempt, status, parts, mr_count, error, created_at
`

type CreateParams struct {
	Team    string    `db:"team" json:"team"`
	Slot    string    `db:"slot" json:"slot"`
	RunDate time.Time `db:"run_date" json:"run_date"`
	Attempt int32     `db:"attempt" json:"attempt"`
	Status  string    `db:"status" json:"status"`
	Parts   int32     `db:"parts" json:"parts"`
	MrCount int32     `db:"mr_count" json:"mr_count"`
	Error   string    `db:"error" json:"error"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.DigestRun, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Team,
		arg.Slot,
		arg.RunDate,
		arg.Attempt,
		arg.Status,
		arg.Parts,
		arg.MrCount,
		arg.Error,
	)
	var i models.DigestRun
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Slot,
		&i.RunDate,
		&i.Attempt,
		&i.Status,
		&i.Parts,
		&i.MrCount,
		&i.Error,
		&i.CreatedAt,
	)
	return &i, err
}

const getByID = `-- name: GetByID :one
SELECT id, team, slot, run_date, attempt, status, parts, mr_count, error, created_at FROM digest_runs WHERE id=$1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.DigestRun, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.DigestRun
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Slot,
		&i.RunDate,
		&i.Attempt,
		&i.Status,
		&i.Parts,
		&i.MrCount,
		&i.Error,
		&i.CreatedAt,
	)
	return &i, err
}
