// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest_runs.sql

package repo_digestrun

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sxwebdev/ai-reviewer/internal/models"
)

const getBySlot = `-- name: GetBySlot :one
SELECT id, team, slot, run_date, attempt, status, parts, mr_count, error, created_at FROM digest_runs
WHERE team = $1
  AND run_date = $2
  AND slot = $3
ORDER BY attempt DESC
LIMIT 1
`

type GetBySlotParams struct {
	Team    string    `db:"team" json:"team"`
	RunDate time.Time `db:"run_date" json:"run_date"`
	Slot    string    `db:"slot" json:"slot"`
}

// GetBySlot returns the most recent run of a slot ("has this slot been sent
// today?").
func (q *Queries) GetBySlot(ctx context.Context, arg GetBySlotParams) (*models.DigestRun, error) {
	row := q.db.QueryRow(ctx, getBySlot, arg.Team, arg.RunDate, arg.Slot)
	var i models.DigestRun
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Slot,
		&i.RunDate,
		&i.Attempt,
		&i.Status,
		&i.Parts,
		&i.MrCount,
		&i.Error,
		&i.CreatedAt,
	)
	return &i, err
}

const getBySlotAttempt = `-- name: GetBySlotAttempt :one
SELECT id, team, slot, run_date, attempt, status, parts, mr_count, error, created_at FROM digest_runs
WHERE team = $1
  AND run_date = $2
  AND slot = $3
  AND attempt = $4
LIMIT 1
`

type GetBySlotAttemptParams struct {
	Team    string    `db:"team" json:"team"`
	RunDate time.Time `db:"run_date" json:"run_date"`
	Slot    string    `db:"slot" json:"slot"`
	Attempt int32     `db:"attempt" json:"attempt"`
}

// GetBySlotAttempt addresses one specific run. It is what the scheduled job must
// use: `digest --force` earlier in the day creates attempt 1, so asking GetBySlot
// whether the 09:00 slot already ran would answer "yes, attempt 1" and the
// scheduled attempt 0 would collide with digest_runs_slot_uniq instead of being
// recognised as a run that has not happened yet.
func (q *Queries) GetBySlotAttempt(ctx context.Context, arg GetBySlotAttemptParams) (*models.DigestRun, error) {
	row := q.db.QueryRow(ctx, getBySlotAttempt,
		arg.Team,
		arg.RunDate,
		arg.Slot,
		arg.Attempt,
	)
	var i models.DigestRun
	err := row.Scan(
		&i.ID,
		&i.Team,
		&i.Slot,
		&i.RunDate,
		&i.Attempt,
		&i.Status,
		&i.Parts,
		&i.MrCount,
		&i.Error,
		&i.CreatedAt,
	)
	return &i, err
}

const nextAttempt = `-- name: NextAttempt :one
SELECT COALESCE(max(attempt) + 1, 0)::int AS next_attempt
FROM digest_runs
WHERE team = $1
  AND run_date = $2
  AND slot = $3
`

type NextAttemptParams struct {
	Team    string    `db:"team" json:"team"`
	RunDate time.Time `db:"run_date" json:"run_date"`
	Slot    string    `db:"slot" json:"slot"`
}

// NextAttempt is what `ai-reviewer digest --force` uses: attempt 0 is the
// scheduled run of a slot (its uniqueness is what stops N replicas doubling it),
// so an explicit repeat has to take the next free number rather than relax the
// index.
func (q *Queries) NextAttempt(ctx context.Context, arg NextAttemptParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextAttempt, arg.Team, arg.RunDate, arg.Slot)
	var next_attempt int32
	err := row.Scan(&next_attempt)
	return next_attempt, err
}

const setStatus = `-- name: SetStatus :exec
UPDATE digest_runs
SET status = $1,
    parts = $2,
    mr_count = $3,
    error = $4
WHERE id = $5
`

type SetStatusParams struct {
	Status  string    `db:"status" json:"status"`
	Parts   int32     `db:"parts" json:"parts"`
	MrCount int32     `db:"mr_count" json:"mr_count"`
	Error   string    `db:"error" json:"error"`
	ID      uuid.UUID `db:"id" json:"id"`
}

// SetStatus closes out the BUILD half of a run: 'built' when the payload is
// assembled and the delivery jobs are queued, 'partial' when some repository
// could not be inspected, 'dry_run' when nothing may be sent, 'failed' when the
// build itself broke. The delivery half is SettleDelivery's job.
func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) error {
	_, err := q.db.Exec(ctx, setStatus,
		arg.Status,
		arg.Parts,
		arg.MrCount,
		arg.Error,
		arg.ID,
	)
	return err
}

const settleDelivery = `-- name: SettleDelivery :many
WITH counts AS (
    SELECT count(*) AS total,
           count(*) FILTER (WHERE status = 'sent') AS sent,
           count(*) FILTER (WHERE status IN ('pending', 'sending')) AS pending
      FROM digest_messages
     WHERE digest_run_id = $1
)
UPDATE digest_runs r
   SET status = CASE
       WHEN c.sent = 0            THEN 'failed'
       WHEN c.sent < c.total      THEN 'partial'
       WHEN r.status = 'partial'  THEN 'partial'
       ELSE 'sent'
   END
  FROM counts c
 WHERE r.id = $1
   AND r.status IN ('built', 'partial')
   AND c.total > 0
   AND c.pending = 0
RETURNING r.status
`

// SettleDelivery recomputes a run's status from its parts once they have all
// stopped moving (plan section 13.5: 'sent' — все части подтверждены, 'partial' —
// часть частей не доставлена).
//
// Without it nothing ever writes 'sent': the build-time statuses are the only
// ones a run ever gets, so a digest whose parts all failed is byte-identical to
// one that was delivered, and `SELECT * FROM digest_runs WHERE status <> 'sent'`
// — the query the schema invites — returns every row that ever existed. It is
// called from slack_send after each part settles; the last part to settle is the
// one whose call finds pending = 0 and writes the answer.
//
// Three guards make it safe to call from every worker on every part:
//
//	c.pending = 0            a run with parts still 'pending'/'sending' has not
//	                         settled; leave the build-time status alone.
//	r.status IN (...)        'dry_run' and 'failed' are terminal build outcomes
//	                         and are never delivery states.
//	the 'partial' arm        a run built on incomplete repository data stays
//	                         'partial' even when every part is delivered —
//	                         promoting it to 'sent' would erase the one fact the
//	                         section 6.6 journal exists to record.
func (q *Queries) SettleDelivery(ctx context.Context, id uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, settleDelivery, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var status string
		if err := rows.Scan(&status); err != nil {
			return nil, err
		}
		items = append(items, status)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
