// Code generated by pgxgen. DO NOT EDIT.
package models

import (
	"database/sql"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/sxwebdev/ai-reviewer/internal/dbtypes"
	"time"
)

type DigestMessage struct {
	ID          uuid.UUID    `db:"id" json:"id"`
	DigestRunID uuid.UUID    `db:"digest_run_id" json:"digest_run_id"`
	PartNo      int32        `db:"part_no" json:"part_no"`
	PartsTotal  int32        `db:"parts_total" json:"parts_total"`
	Channel     string       `db:"channel" json:"channel"`
	Payload     dbtypes.JSON `db:"payload" json:"payload"`
	Status      string       `db:"status" json:"status"`
	SlackTs     string       `db:"slack_ts" json:"slack_ts"`
	Error       string       `db:"error" json:"error"`
	SentAt      sql.NullTime `db:"sent_at" json:"sent_at"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
}

type DigestRun struct {
	ID               uuid.UUID `db:"id" json:"id"`
	Team             string    `db:"team" json:"team"`
	Slot             string    `db:"slot" json:"slot"`
	RunDate          time.Time `db:"run_date" json:"run_date"`
	Attempt          int32     `db:"attempt" json:"attempt"`
	Status           string    `db:"status" json:"status"`
	Parts            int32     `db:"parts" json:"parts"`
	MrCount          int32     `db:"mr_count" json:"mr_count"`
	Error            string    `db:"error" json:"error"`
	CreatedAt        time.Time `db:"created_at" json:"created_at"`
	LinearIssueCount int32     `db:"linear_issue_count" json:"linear_issue_count"`
}

type MrFinding struct {
	ID           uuid.UUID     `db:"id" json:"id"`
	ReviewID     uuid.UUID     `db:"review_id" json:"review_id"`
	ProjectID    int64         `db:"project_id" json:"project_id"`
	MrIid        int64         `db:"mr_iid" json:"mr_iid"`
	Fingerprint  string        `db:"fingerprint" json:"fingerprint"`
	Severity     string        `db:"severity" json:"severity"`
	Category     string        `db:"category" json:"category"`
	FilePath     string        `db:"file_path" json:"file_path"`
	Title        string        `db:"title" json:"title"`
	Body         string        `db:"body" json:"body"`
	PositionJson dbtypes.JSON  `db:"position_json" json:"position_json"`
	Pass         string        `db:"pass" json:"pass"`
	Verification string        `db:"verification" json:"verification"`
	NoteID       sql.NullInt64 `db:"note_id" json:"note_id"`
	PublishedAt  sql.NullTime  `db:"published_at" json:"published_at"`
	CreatedAt    time.Time     `db:"created_at" json:"created_at"`
}

type MrReview struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	ProjectID       int64           `db:"project_id" json:"project_id"`
	ProjectPath     string          `db:"project_path" json:"project_path"`
	Team            string          `db:"team" json:"team"`
	MrIid           int64           `db:"mr_iid" json:"mr_iid"`
	HeadSha         string          `db:"head_sha" json:"head_sha"`
	BaseSha         string          `db:"base_sha" json:"base_sha"`
	StartSha        string          `db:"start_sha" json:"start_sha"`
	Status          string          `db:"status" json:"status"`
	FindingsCount   int32           `db:"findings_count" json:"findings_count"`
	RiskLevel       string          `db:"risk_level" json:"risk_level"`
	Summary         string          `db:"summary" json:"summary"`
	PipelineJson    dbtypes.JSON    `db:"pipeline_json" json:"pipeline_json"`
	RiskJson        dbtypes.JSON    `db:"risk_json" json:"risk_json"`
	CostUsd         decimal.Decimal `db:"cost_usd" json:"cost_usd"`
	DurationMs      int64           `db:"duration_ms" json:"duration_ms"`
	Error           string          `db:"error" json:"error"`
	Attempt         int32           `db:"attempt" json:"attempt"`
	PublishAttempts int32           `db:"publish_attempts" json:"publish_attempts"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
}
