// Code generated by pgxgen. DO NOT EDIT.
package repo_digestmessage

import (
	"github.com/gobeam/stringy"
	"strings"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameDigestMessages TableName = "digest_messages"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameDigestMessagesId          ColumnName = "id"
	ColumnNameDigestMessagesDigestRunId ColumnName = "digest_run_id"
	ColumnNameDigestMessagesPartNo      ColumnName = "part_no"
	ColumnNameDigestMessagesPartsTotal  ColumnName = "parts_total"
	ColumnNameDigestMessagesChannel     ColumnName = "channel"
	ColumnNameDigestMessagesPayload     ColumnName = "payload"
	ColumnNameDigestMessagesStatus      ColumnName = "status"
	ColumnNameDigestMessagesSlackTs     ColumnName = "slack_ts"
	ColumnNameDigestMessagesError       ColumnName = "error"
	ColumnNameDigestMessagesSentAt      ColumnName = "sent_at"
	ColumnNameDigestMessagesCreatedAt   ColumnName = "created_at"
)

func DigestMessagesColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameDigestMessagesId,
		ColumnNameDigestMessagesDigestRunId,
		ColumnNameDigestMessagesPartNo,
		ColumnNameDigestMessagesPartsTotal,
		ColumnNameDigestMessagesChannel,
		ColumnNameDigestMessagesPayload,
		ColumnNameDigestMessagesStatus,
		ColumnNameDigestMessagesSlackTs,
		ColumnNameDigestMessagesError,
		ColumnNameDigestMessagesSentAt,
		ColumnNameDigestMessagesCreatedAt,
	}
}
