// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest_messages_gen.sql

package repo_digestmessage

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sxwebdev/ai-reviewer/internal/dbtypes"
	"github.com/sxwebdev/ai-reviewer/internal/models"
)

const create = `-- name: Create :one
INSERT INTO digest_messages (digest_run_id, part_no, parts_total, channel, payload, status, slack_ts, error, sent_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
	RETURNING id, digest_run_id, part_no, parts_total, channel, payload, status, slack_ts, error, sent_at, created_at
`

type CreateParams struct {
	DigestRunID uuid.UUID    `db:"digest_run_id" json:"digest_run_id"`
	PartNo      int32        `db:"part_no" json:"part_no"`
	PartsTotal  int32        `db:"parts_total" json:"parts_total"`
	Channel     string       `db:"channel" json:"channel"`
	Payload     dbtypes.JSON `db:"payload" json:"payload"`
	Status      string       `db:"status" json:"status"`
	SlackTs     string       `db:"slack_ts" json:"slack_ts"`
	Error       string       `db:"error" json:"error"`
	SentAt      sql.NullTime `db:"sent_at" json:"sent_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.DigestMessage, error) {
	row := q.db.QueryRow(ctx, create,
		arg.DigestRunID,
		arg.PartNo,
		arg.PartsTotal,
		arg.Channel,
		arg.Payload,
		arg.Status,
		arg.SlackTs,
		arg.Error,
		arg.SentAt,
	)
	var i models.DigestMessage
	err := row.Scan(
		&i.ID,
		&i.DigestRunID,
		&i.PartNo,
		&i.PartsTotal,
		&i.Channel,
		&i.Payload,
		&i.Status,
		&i.SlackTs,
		&i.Error,
		&i.SentAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getByID = `-- name: GetByID :one
SELECT id, digest_run_id, part_no, parts_total, channel, payload, status, slack_ts, error, sent_at, created_at FROM digest_messages WHERE id=$1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.DigestMessage, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.DigestMessage
	err := row.Scan(
		&i.ID,
		&i.DigestRunID,
		&i.PartNo,
		&i.PartsTotal,
		&i.Channel,
		&i.Payload,
		&i.Status,
		&i.SlackTs,
		&i.Error,
		&i.SentAt,
		&i.CreatedAt,
	)
	return &i, err
}
