// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest_messages.sql

package repo_digestmessage

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/ai-reviewer/internal/models"
)

const claimForSend = `-- name: ClaimForSend :one
WITH prev AS (
    SELECT dm.id, dm.status FROM digest_messages dm WHERE dm.id = $1 FOR UPDATE
), claimed AS (
    UPDATE digest_messages m
       SET status = 'sending'
      FROM prev
     WHERE m.id = prev.id AND prev.status IN ('pending', 'sending')
    RETURNING m.id
)
SELECT prev.status::text AS status_before,
       ((SELECT count(*) FROM claimed) > 0)::boolean AS claimed
FROM prev
`

type ClaimForSendRow struct {
	StatusBefore string `db:"status_before" json:"status_before"`
	Claimed      bool   `db:"claimed" json:"claimed"`
}

// ClaimForSend is step 1 of the slack_send idempotency protocol (section 6.4).
// chat.postMessage has no idempotency key, so the window "the POST went through
// but the worker died before recording it" is closed by state in the database.
//
// The CTE exists because RETURNING hands back the *new* row values, while the
// whole decision hangs on the status the row had before the claim:
//
//	status_before='sent'                  -> job is a no-op (already delivered)
//	status_before IN ('failed','dry_run') -> job is a no-op (nothing to resend)
//	status_before='pending'               -> ordinary first delivery
//	status_before='sending'               -> a previous attempt died between the
//	                                         POST and the result write; the
//	                                         message is sent again on purpose
//	                                         (a duplicate in the channel is
//	                                         noise, a lost digest is a team not
//	                                         acting), with a warning and
//	                                         slack_resend_uncertain_total.
//
// FOR UPDATE is what forces the CTE to be materialized rather than inlined, so
// prev really is the pre-UPDATE snapshot.
//
// It does NOT serialize two workers into a winner and a loser, and nothing here
// should be read as if it did: the second claimer blocks on the row lock, then
// re-reads the *post*-update tuple, sees status='sending' and takes the resend
// branch — so both would POST. That two claimers never coexist is guaranteed by
// River's in-flight uniqueness on slack_send (one job per digest_message_id),
// not by this statement. Anything that introduces a second claimer — a manual
// re-drive, a sweep for stuck rows, RescueStuckJobsAfter shortened below a job's
// runtime — is an immediate double-post, not a race that mostly resolves.
func (q *Queries) ClaimForSend(ctx context.Context, id uuid.UUID) (*ClaimForSendRow, error) {
	row := q.db.QueryRow(ctx, claimForSend, id)
	var i ClaimForSendRow
	err := row.Scan(&i.StatusBefore, &i.Claimed)
	return &i, err
}

const listByRun = `-- name: ListByRun :many
SELECT id, digest_run_id, part_no, parts_total, channel, payload, status, slack_ts, error, sent_at, created_at FROM digest_messages
WHERE digest_run_id = $1
ORDER BY part_no
`

func (q *Queries) ListByRun(ctx context.Context, digestRunID uuid.UUID) ([]*models.DigestMessage, error) {
	rows, err := q.db.Query(ctx, listByRun, digestRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.DigestMessage{}
	for rows.Next() {
		var i models.DigestMessage
		if err := rows.Scan(
			&i.ID,
			&i.DigestRunID,
			&i.PartNo,
			&i.PartsTotal,
			&i.Channel,
			&i.Payload,
			&i.Status,
			&i.SlackTs,
			&i.Error,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFailed = `-- name: MarkFailed :exec
UPDATE digest_messages
SET status = 'failed',
    error = $1
WHERE id = $2
`

// The parameter is @error_text rather than @error so the generated positional
// argument does not shadow the predeclared `error` identifier.
func (q *Queries) MarkFailed(ctx context.Context, errorText string, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, markFailed, errorText, iD)
	return err
}

const markSent = `-- name: MarkSent :exec
UPDATE digest_messages
SET status = 'sent',
    slack_ts = $1,
    sent_at = now(),
    error = ''
WHERE id = $2
`

func (q *Queries) MarkSent(ctx context.Context, slackTs string, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSent, slackTs, iD)
	return err
}

const releaseClaim = `-- name: ReleaseClaim :exec
UPDATE digest_messages
SET status = 'pending',
    error = $1
WHERE id = $2 AND status = 'sending'
`

// ReleaseClaim hands a claimed row back for an ordinary retry, and it is what
// keeps slack_resend_uncertain_total meaning what section 14.3 says it means.
//
// 'sending' is supposed to say "a previous attempt died between the POST and the
// result write" — the one case where a duplicate may really be in the channel.
// But a retryable delivery failure also left the row at 'sending', so the next
// attempt logged "previous delivery outcome is unknown" and bumped the counter
// on `ratelimited`, the most common answer Slack gives and one that explicitly
// means NOT delivered. The caller therefore releases the claim whenever Slack
// answered at the application layer, and leaves the row 'sending' only when the
// outcome is genuinely unknown (transport failure, 5xx, or a crash).
func (q *Queries) ReleaseClaim(ctx context.Context, errorText string, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseClaim, errorText, iD)
	return err
}
