// Code generated by pgxgen. DO NOT EDIT.
package repo_finding

import (
	"github.com/gobeam/stringy"
	"strings"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameMrFindings TableName = "mr_findings"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameMrFindingsId           ColumnName = "id"
	ColumnNameMrFindingsReviewId     ColumnName = "review_id"
	ColumnNameMrFindingsProjectId    ColumnName = "project_id"
	ColumnNameMrFindingsMrIid        ColumnName = "mr_iid"
	ColumnNameMrFindingsFingerprint  ColumnName = "fingerprint"
	ColumnNameMrFindingsSeverity     ColumnName = "severity"
	ColumnNameMrFindingsCategory     ColumnName = "category"
	ColumnNameMrFindingsFilePath     ColumnName = "file_path"
	ColumnNameMrFindingsTitle        ColumnName = "title"
	ColumnNameMrFindingsBody         ColumnName = "body"
	ColumnNameMrFindingsPositionJson ColumnName = "position_json"
	ColumnNameMrFindingsPass         ColumnName = "pass"
	ColumnNameMrFindingsVerification ColumnName = "verification"
	ColumnNameMrFindingsNoteId       ColumnName = "note_id"
	ColumnNameMrFindingsPublishedAt  ColumnName = "published_at"
	ColumnNameMrFindingsCreatedAt    ColumnName = "created_at"
)

func MrFindingsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameMrFindingsId,
		ColumnNameMrFindingsReviewId,
		ColumnNameMrFindingsProjectId,
		ColumnNameMrFindingsMrIid,
		ColumnNameMrFindingsFingerprint,
		ColumnNameMrFindingsSeverity,
		ColumnNameMrFindingsCategory,
		ColumnNameMrFindingsFilePath,
		ColumnNameMrFindingsTitle,
		ColumnNameMrFindingsBody,
		ColumnNameMrFindingsPositionJson,
		ColumnNameMrFindingsPass,
		ColumnNameMrFindingsVerification,
		ColumnNameMrFindingsNoteId,
		ColumnNameMrFindingsPublishedAt,
		ColumnNameMrFindingsCreatedAt,
	}
}
