// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package repo_finding

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/ai-reviewer/internal/dbtypes"
	"github.com/sxwebdev/ai-reviewer/internal/models"
)

const insert = `-- name: Insert :execrows
INSERT INTO mr_findings (
    review_id, project_id, mr_iid, fingerprint, severity, category,
    file_path, title, body, position_json, pass, verification
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
ON CONFLICT (project_id, mr_iid, fingerprint) DO UPDATE
   SET review_id     = EXCLUDED.review_id,
       severity      = EXCLUDED.severity,
       body          = EXCLUDED.body,
       position_json = EXCLUDED.position_json,
       pass          = EXCLUDED.pass,
       verification  = EXCLUDED.verification
 WHERE mr_findings.note_id IS NULL
   AND NOT EXISTS (
       SELECT 1 FROM mr_reviews r
        WHERE r.id = mr_findings.review_id
          AND r.status = 'reviewed'
   )
`

type InsertParams struct {
	ReviewID     uuid.UUID    `db:"review_id" json:"review_id"`
	ProjectID    int64        `db:"project_id" json:"project_id"`
	MrIid        int64        `db:"mr_iid" json:"mr_iid"`
	Fingerprint  string       `db:"fingerprint" json:"fingerprint"`
	Severity     string       `db:"severity" json:"severity"`
	Category     string       `db:"category" json:"category"`
	FilePath     string       `db:"file_path" json:"file_path"`
	Title        string       `db:"title" json:"title"`
	Body         string       `db:"body" json:"body"`
	PositionJson dbtypes.JSON `db:"position_json" json:"position_json"`
	Pass         string       `db:"pass" json:"pass"`
	Verification string       `db:"verification" json:"verification"`
}

// Insert is the only way findings enter the database. The ON CONFLICT clause is
// mandatory (plan section 5.2): a duplicate fingerprint is an expected outcome —
// the engine may fail to filter it when reading discussions degrades — and must
// never abort the transaction that persists the whole review.
//
// It is DO UPDATE rather than DO NOTHING because of the other half of the
// section 10.3 trap. A dry-run review A stores fingerprint F with note_id NULL.
// ListPublishedFingerprints rightly omits F, so the engine emits it again on
// review B — but under DO NOTHING the row stays attached to A, so
// ListUnpublishedByReview(B) never sees it and PublishReview(B) posts nothing,
// while A (status 'dry_run') is never published either. F would be stuck
// forever: the fingerprint does not depend on the head SHA, so no later push
// frees it. Re-attaching the row to the newest review is what makes the finding
// reachable again.
//
// `WHERE mr_findings.note_id IS NULL` is the counterweight: a row that already
// reached GitLab stays bound to the review that published it, and its
// note_id/published_at are never clobbered — that binding is the audit trail and
// the dedupe key at once. created_at deliberately keeps the first-seen time.
//
// The NOT EXISTS clause is the second counterweight, and it is what keeps
// re-attachment from racing publication. `status='reviewed'` means "persisted,
// publication pending or in flight", and publish uniqueness is ByArgs(review_id)
// — so two publishers for two reviews of the SAME merge request are not mutually
// excluded. Without the clause, review B's persist transaction can move A's
// still-unposted finding to B while publish_review(A) is between its snapshot
// read and its POST, which produces exactly the two outcomes section 10.4 says
// are impossible: the same comment posted twice (A posts from its snapshot, B
// posts because the row is now its own), or — if B is a dry run — a review
// marked 'succeeded' having posted none of its findings, because they were
// stolen into a review that will never publish.
//
// A finding is therefore only re-attached when nobody is going to publish it
// where it is: dry_run (the section 10.3 trap this DO UPDATE exists for),
// abandoned (publication gave up) or succeeded-but-unrecorded. Everything else
// stays put and the caller is told so.
//
// :execrows therefore reports "this finding is now attached to this review and
// awaiting publication" (1) versus "somebody else owns it — already published,
// or attached to a review whose publication is still pending" (0). It is no
// longer a pure duplicate detector, but the caller's branch is unchanged.
func (q *Queries) Insert(ctx context.Context, arg InsertParams) (int64, error) {
	result, err := q.db.Exec(ctx, insert,
		arg.ReviewID,
		arg.ProjectID,
		arg.MrIid,
		arg.Fingerprint,
		arg.Severity,
		arg.Category,
		arg.FilePath,
		arg.Title,
		arg.Body,
		arg.PositionJson,
		arg.Pass,
		arg.Verification,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listByReview = `-- name: ListByReview :many
SELECT id, review_id, project_id, mr_iid, fingerprint, severity, category, file_path, title, body, position_json, pass, verification, note_id, published_at, created_at FROM mr_findings
WHERE review_id = $1
ORDER BY created_at, id
`

// ListByReview returns every finding a review produced, published or not. It
// backs the section 11 prior-review continuity block: the next review of the same
// MR is told what the previous one raised and whether it reached GitLab, so it
// does not spend tokens re-deriving findings the deterministic fingerprint gate
// would drop anyway.
func (q *Queries) ListByReview(ctx context.Context, reviewID uuid.UUID) ([]*models.MrFinding, error) {
	rows, err := q.db.Query(ctx, listByReview, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.MrFinding{}
	for rows.Next() {
		var i models.MrFinding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.ProjectID,
			&i.MrIid,
			&i.Fingerprint,
			&i.Severity,
			&i.Category,
			&i.FilePath,
			&i.Title,
			&i.Body,
			&i.PositionJson,
			&i.Pass,
			&i.Verification,
			&i.NoteID,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedFingerprints = `-- name: ListPublishedFingerprints :many
SELECT fingerprint FROM mr_findings
WHERE project_id = $1
  AND mr_iid = $2
  AND note_id IS NOT NULL
`

// ListPublishedFingerprints builds ExistingFingerprints for the engine
// (plan section 10.3).
//
// `note_id IS NOT NULL` is load-bearing: dedupe must mean "this finding is
// already hanging in GitLab", not "we once computed it". Without it every
// dry-run writes findings with note_id = NULL, and once publishing is switched
// on the engine treats them as duplicates and never publishes them — the
// fingerprint does not depend on the head SHA, so new pushes cannot fix it.
func (q *Queries) ListPublishedFingerprints(ctx context.Context, projectID int64, mrIid int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listPublishedFingerprints, projectID, mrIid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var fingerprint string
		if err := rows.Scan(&fingerprint); err != nil {
			return nil, err
		}
		items = append(items, fingerprint)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedByReview = `-- name: ListUnpublishedByReview :many
SELECT id, review_id, project_id, mr_iid, fingerprint, severity, category, file_path, title, body, position_json, pass, verification, note_id, published_at, created_at FROM mr_findings
WHERE review_id = $1
  AND note_id IS NULL
ORDER BY created_at, id
`

// ListUnpublishedByReview drives the idempotent publish_review job: a retry
// after a crash mid-way posts only what is still missing.
func (q *Queries) ListUnpublishedByReview(ctx context.Context, reviewID uuid.UUID) ([]*models.MrFinding, error) {
	rows, err := q.db.Query(ctx, listUnpublishedByReview, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.MrFinding{}
	for rows.Next() {
		var i models.MrFinding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.ProjectID,
			&i.MrIid,
			&i.Fingerprint,
			&i.Severity,
			&i.Category,
			&i.FilePath,
			&i.Title,
			&i.Body,
			&i.PositionJson,
			&i.Pass,
			&i.Verification,
			&i.NoteID,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPublished = `-- name: MarkPublished :exec
UPDATE mr_findings
SET note_id = $1::bigint,
    published_at = now()
WHERE id = $2
`

// MarkPublished is written immediately after each successful POST, not batched
// at the end — that is what makes a crash inside publication cost at most one
// duplicate-free retry. The cast keeps the parameter a plain int64 even though
// the column is nullable.
func (q *Queries) MarkPublished(ctx context.Context, noteID int64, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPublished, noteID, iD)
	return err
}
