// Code generated by pgxgen. DO NOT EDIT.
package repo_review

import (
	"github.com/gobeam/stringy"
	"strings"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameMrReviews TableName = "mr_reviews"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameMrReviewsId              ColumnName = "id"
	ColumnNameMrReviewsProjectId       ColumnName = "project_id"
	ColumnNameMrReviewsProjectPath     ColumnName = "project_path"
	ColumnNameMrReviewsTeam            ColumnName = "team"
	ColumnNameMrReviewsMrIid           ColumnName = "mr_iid"
	ColumnNameMrReviewsHeadSha         ColumnName = "head_sha"
	ColumnNameMrReviewsBaseSha         ColumnName = "base_sha"
	ColumnNameMrReviewsStartSha        ColumnName = "start_sha"
	ColumnNameMrReviewsStatus          ColumnName = "status"
	ColumnNameMrReviewsFindingsCount   ColumnName = "findings_count"
	ColumnNameMrReviewsRiskLevel       ColumnName = "risk_level"
	ColumnNameMrReviewsSummary         ColumnName = "summary"
	ColumnNameMrReviewsPipelineJson    ColumnName = "pipeline_json"
	ColumnNameMrReviewsRiskJson        ColumnName = "risk_json"
	ColumnNameMrReviewsCostUsd         ColumnName = "cost_usd"
	ColumnNameMrReviewsDurationMs      ColumnName = "duration_ms"
	ColumnNameMrReviewsError           ColumnName = "error"
	ColumnNameMrReviewsAttempt         ColumnName = "attempt"
	ColumnNameMrReviewsPublishAttempts ColumnName = "publish_attempts"
	ColumnNameMrReviewsCreatedAt       ColumnName = "created_at"
)

func MrReviewsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameMrReviewsId,
		ColumnNameMrReviewsProjectId,
		ColumnNameMrReviewsProjectPath,
		ColumnNameMrReviewsTeam,
		ColumnNameMrReviewsMrIid,
		ColumnNameMrReviewsHeadSha,
		ColumnNameMrReviewsBaseSha,
		ColumnNameMrReviewsStartSha,
		ColumnNameMrReviewsStatus,
		ColumnNameMrReviewsFindingsCount,
		ColumnNameMrReviewsRiskLevel,
		ColumnNameMrReviewsSummary,
		ColumnNameMrReviewsPipelineJson,
		ColumnNameMrReviewsRiskJson,
		ColumnNameMrReviewsCostUsd,
		ColumnNameMrReviewsDurationMs,
		ColumnNameMrReviewsError,
		ColumnNameMrReviewsAttempt,
		ColumnNameMrReviewsPublishAttempts,
		ColumnNameMrReviewsCreatedAt,
	}
}
