// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mr_reviews_gen.sql

package repo_review

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/sxwebdev/ai-reviewer/internal/dbtypes"
	"github.com/sxwebdev/ai-reviewer/internal/models"
)

const create = `-- name: Create :one
INSERT INTO mr_reviews (project_id, project_path, team, mr_iid, head_sha, base_sha, start_sha, status, findings_count, risk_level, summary, pipeline_json, risk_json, cost_usd, duration_ms, error, attempt, publish_attempts)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
	RETURNING id, project_id, project_path, team, mr_iid, head_sha, base_sha, start_sha, status, findings_count, risk_level, summary, pipeline_json, risk_json, cost_usd, duration_ms, error, attempt, publish_attempts, created_at
`

type CreateParams struct {
	ProjectID       int64           `db:"project_id" json:"project_id"`
	ProjectPath     string          `db:"project_path" json:"project_path"`
	Team            string          `db:"team" json:"team"`
	MrIid           int64           `db:"mr_iid" json:"mr_iid"`
	HeadSha         string          `db:"head_sha" json:"head_sha"`
	BaseSha         string          `db:"base_sha" json:"base_sha"`
	StartSha        string          `db:"start_sha" json:"start_sha"`
	Status          string          `db:"status" json:"status"`
	FindingsCount   int32           `db:"findings_count" json:"findings_count"`
	RiskLevel       string          `db:"risk_level" json:"risk_level"`
	Summary         string          `db:"summary" json:"summary"`
	PipelineJson    dbtypes.JSON    `db:"pipeline_json" json:"pipeline_json"`
	RiskJson        dbtypes.JSON    `db:"risk_json" json:"risk_json"`
	CostUsd         decimal.Decimal `db:"cost_usd" json:"cost_usd"`
	DurationMs      int64           `db:"duration_ms" json:"duration_ms"`
	Error           string          `db:"error" json:"error"`
	Attempt         int32           `db:"attempt" json:"attempt"`
	PublishAttempts int32           `db:"publish_attempts" json:"publish_attempts"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.MrReview, error) {
	row := q.db.QueryRow(ctx, create,
		arg.ProjectID,
		arg.ProjectPath,
		arg.Team,
		arg.MrIid,
		arg.HeadSha,
		arg.BaseSha,
		arg.StartSha,
		arg.Status,
		arg.FindingsCount,
		arg.RiskLevel,
		arg.Summary,
		arg.PipelineJson,
		arg.RiskJson,
		arg.CostUsd,
		arg.DurationMs,
		arg.Error,
		arg.Attempt,
		arg.PublishAttempts,
	)
	var i models.MrReview
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectPath,
		&i.Team,
		&i.MrIid,
		&i.HeadSha,
		&i.BaseSha,
		&i.StartSha,
		&i.Status,
		&i.FindingsCount,
		&i.RiskLevel,
		&i.Summary,
		&i.PipelineJson,
		&i.RiskJson,
		&i.CostUsd,
		&i.DurationMs,
		&i.Error,
		&i.Attempt,
		&i.PublishAttempts,
		&i.CreatedAt,
	)
	return &i, err
}

const getByID = `-- name: GetByID :one
SELECT id, project_id, project_path, team, mr_iid, head_sha, base_sha, start_sha, status, findings_count, risk_level, summary, pipeline_json, risk_json, cost_usd, duration_ms, error, attempt, publish_attempts, created_at FROM mr_reviews WHERE id=$1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.MrReview, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.MrReview
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectPath,
		&i.Team,
		&i.MrIid,
		&i.HeadSha,
		&i.BaseSha,
		&i.StartSha,
		&i.Status,
		&i.FindingsCount,
		&i.RiskLevel,
		&i.Summary,
		&i.PipelineJson,
		&i.RiskJson,
		&i.CostUsd,
		&i.DurationMs,
		&i.Error,
		&i.Attempt,
		&i.PublishAttempts,
		&i.CreatedAt,
	)
	return &i, err
}
